import "./globals.css";
import prisma from "@/lib/db";

import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Header } from "@/components/site-header";
import { Inter as FontSans } from "next/font/google";

import { unstable_noStore as noStore } from "next/cache";
import { ThemeProvider } from "@/components/theme-provider";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Saas Next App",
  description: "Generated by create next app",
};

async function getData(userId: string) {
  noStore();
  if (userId) {
    const data = await prisma.user.findUnique({
      where: {
        id: userId,
      },
      select: {
        colorScheme: true,
      },
    });
    return data;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = getKindeServerSession();
  const user = await getUser();
  const data = await getData(user?.id as string);

  return (
    <html lang="en">
      <body
        className={cn(
          `min-h-screen bg-background font-sans antialiased ${
            data?.colorScheme ?? "theme-slate"
          }`,
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
